# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-20 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id',
            new_name='face_id',
        ),
    ]
