# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-29 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190420_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='as', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='as', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='as', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='as', max_length=10),
        ),
    ]
