# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190429_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job',
            field=models.CharField(default='sd', max_length=15),
            preserve_default=False,
        ),
    ]
